version: "3.9"
services:
  db:
    image: postgres:14.6-bullseye
    hostname: db
    ports:
      - "5433:5433"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    user: 1000:1000
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 2G
    restart: on-failure
    command: -p 5433
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "5"
    environment:
      POSTGRES_DB: "PlayPeakDB"
      POSTGRES_USER: "playpeak"
      POSTGRES_PASSWORD: "playpeak"
      PGDATA: /var/lib/postgresql/data/my-db/
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 80s
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

  backend:
    container_name: nestapp
    hostname: backend
    build:
      context: ./play-peak-backend
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DATABASE_URL: postgresql://playpeak:playpeak@db:5433/PlayPeakDB
      CLERK_SECRET_KEY: sk_test_VFHdlYZjapUKn7jb3I7zbNl1RmcVBpbYqOYkGSVizs
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_dmFsaWQtZ29sZGZpc2gtODMuY2xlcmsuYWNjb3VudHMuZGV2JA
      WEBHOOK_SECRET: whsec_paTPEzcy/g85UsdwLidLSM07Da2N1q1E
      MIGRATE: true
      SEED: true
    depends_on:
      - db

  frontend:
    container_name: nextapp
    build:
      context: ./play-peak-frontend
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_dmFsaWQtZ29sZGZpc2gtODMuY2xlcmsuYWNjb3VudHMuZGV2JA
      CLERK_SECRET_KEY: sk_test_VFHdlYZjapUKn7jb3I7zbNl1RmcVBpbYqOYkGSVizs
      API_URL: http://backend:3001
    depends_on:
      - backend
  # nginx:
  #   image: nginx:1.17.10-alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - type: bind
  #       source: ./nginx.conf
  #       target: /etc/nginx/conf.d/default.conf
  #   #     - /home/playpeakdev/certbot/conf:/etc/letsencrypt
  #   #     - /home/playpeakdev/certbot/www:/var/www/certbot
  #   links:
  #     - frontend
  #   depends_on:
  #     - frontend
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.5"
  #         memory: 1G
  #   restart: on-failure
  #   #   logging:
  #   #     driver: json-file
  #   #     options:
  #   #       max-size: '200k'
  #   #       max-file: '5'
  #   healthcheck:
  #     test: ["CMD", "curl", "http://localhost:80/healthcheck"]
  #     interval: 15s
  #     timeout: 5s
  #     retries: 3
  #     start_period: 30s
